spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/stonksdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234567}
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true