spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: stonkstcc@gmail.com
    password: rujhmzehuifcizxo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev
  jpa:
    open-in-view: false
server:
  servlet:
    context-path: /api/v1
jwt:
  secret: ${JWT_SECRET:stonks123456}
  duration: 86400
security:
  oauth2:
    client:
      client-id: ${CLIENT_ID:stonks}
      client-secret: ${CLIENT_SECRET:stonks123456}