insert into tb_games (name) values('bagatelle');
insert into tb_games (name) values('balkline billiards');
insert into tb_games (name) values('baseball');
insert into tb_games (name) values('carom billiards');
insert into tb_games (name) values('eight ball');
insert into tb_games (name) values('golf');
insert into tb_games (name) values('pocket billiards');
insert into tb_games (name) values('pool');
insert into tb_games (name) values('pyramids');
insert into tb_games (name) values('straight-rail billiards');
insert into tb_games (name) values('acey-deucey');
insert into tb_games (name) values('backgammon');
insert into tb_games (name) values('checkers');
insert into tb_games (name) values('chess');
insert into tb_games (name) values('Chinese chess');
insert into tb_games (name) values('go');
insert into tb_games (name) values('goose');
insert into tb_games (name) values('Monopoly');
insert into tb_games (name) values('Nine Men’s Morris');
insert into tb_games (name) values('nyout');
insert into tb_games (name) values('Pachisi');
insert into tb_games (name) values('Polish checkers');
insert into tb_games (name) values('Scrabble');
insert into tb_games (name) values('shogi');
insert into tb_games (name) values('snooker');
insert into tb_games (name) values('Turkish checkers');

insert into TB_ROLES(authority) values ('ROLE_PLAYER');
insert into TB_ROLES(authority) values ('ROLE_TEAM');

insert into tb_users (role_id, first_name, last_name, email, password, cpf, is_open_to_work) values (1, 'Gustavo', 'Silva', 'gustavo.filho.gts@gmail.com', '$2a$12$PWugiEfMzTk71bKDL6AdXOaEEXNSrfiP6FdODa6G.NX75Khgyu7Ue', '523.132.298-62', true);
insert into tb_players (level, years_of_experience, id) values (1, 5, 1);

insert into tb_users (role_id, first_name, last_name, email, password, cpf, is_open_to_work) values (2, 'Gustavo', 'Silva', 'gustavo.tiago.gts@gmail.com', '$2a$12$PWugiEfMzTk71bKDL6AdXOaEEXNSrfiP6FdODa6G.NX75Khgyu7Ue', '623.132.298-62', true);
insert into tb_players (level, years_of_experience, id) values (2, 5, 2);

insert into tb_users (role_id, first_name, last_name, email, password, cpf, is_open_to_work) values (1, 'Mateus', 'Zucheli', 'mateuszucheli@hotmail.com', '$2a$12$PWugiEfMzTk71bKDL6AdXOaEEXNSrfiP6FdODa6G.NX75Khgyu7Ue', '723.132.298-62', true);
insert into tb_players (level, years_of_experience, id) values (1, 5, 3);

insert into tb_vacancies (user_id, name, description, vacancy_type, start_date, end_date) values (1, 'Vaga 1', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'TEAM', '2022-09-23', '2022-10-23');
insert into tb_vacancies (user_id, name, description, vacancy_type, start_date, end_date) values (2, 'Vaga 2', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'TEAM', '2022-05-22', '2022-06-23');
insert into tb_vacancies (user_id, name, description, vacancy_type, start_date, end_date) values (1, 'Vaga 3', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'TEAM', '2022-03-23', '2022-06-23');
insert into tb_vacancies (user_id, name, description, vacancy_type, start_date, end_date) values (1, 'Vaga 4', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'TEAM', '2022-02-23', '2022-03-23');
insert into tb_vacancies (user_id, name, description, vacancy_type, start_date, end_date) values (1, 'Vaga 5', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'TEAM', '2022-01-23', '2022-02-23');
insert into tb_vacancies (user_id, name, description, vacancy_type, start_date, end_date) values (1, 'Vaga 6', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'TEAM', '2021-09-23', '2021-10-23');
insert into tb_vacancies (user_id, name, description, vacancy_type, start_date, end_date) values (1, 'Vaga 7', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'TEAM', '2021-09-23', '2021-10-23');
insert into tb_vacancies (user_id, name, description, vacancy_type, start_date, end_date) values (1, 'Vaga 8', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'TEAM', '2021-09-23', '2021-10-23');
insert into tb_vacancies (name, description, vacancy_type, start_date, end_date) values ('Vaga 9', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'TEAM', '2021-09-23', '2021-10-23');
insert into tb_vacancies (name, description, vacancy_type, start_date, end_date) values ('Vaga 10', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'TEAM', '2020-09-12', '2020-10-16');
insert into tb_vacancies (name, description, vacancy_type, start_date, end_date) values ('Vaga 11', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'TEAM', '2020-09-11', '2020-10-23');
insert into tb_vacancies (name, description, vacancy_type, start_date, end_date) values ('Vaga 12', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'TEAM', '2020-09-12', '2020-10-30');
insert into tb_vacancies (name, description, vacancy_type, start_date, end_date) values ('Vaga 13', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'TEAM', '2020-09-25', '2020-10-15');
insert into tb_vacancies (name, description, vacancy_type, start_date, end_date) values ('Vaga 14', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'TEAM', '2020-09-11', '2020-10-12');
insert into tb_vacancies (name, description, vacancy_type, start_date, end_date) values ('Vaga 15', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'TEAM', '2020-09-01', '2020-10-10');
insert into tb_vacancies (name, description, vacancy_type, start_date, end_date) values ('Vaga 16', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'TEAM', '2020-09-02', '2020-10-03');
insert into tb_vacancies (name, description, vacancy_type, start_date, end_date) values ('Vaga 17', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'TEAM', '2020-09-03', '2020-10-06');

INSERT INTO tb_teams (years_of_experience, name, description, vacancy_id) VALUES (10, 'Guardiões da Galáxia', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 1);
INSERT INTO tb_teams (years_of_experience, name, description, vacancy_id) VALUES (5, 'Vingadores', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 2);
INSERT INTO tb_teams (years_of_experience, name, description, vacancy_id) VALUES (3, 'Liga da Justiça', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 3);
INSERT INTO tb_teams (years_of_experience, name, description) VALUES (2, 'Os Supremos', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
INSERT INTO tb_teams (years_of_experience, name, description) VALUES (7, 'Justiça Jovem', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
INSERT INTO tb_teams (years_of_experience, name, description) VALUES (3, 'Ben 10', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');

insert into TB_TEAMS_GAMES (team_id, game_id) values (1,1);
insert into TB_TEAMS_GAMES (team_id, game_id) values (1,2);
insert into TB_TEAMS_GAMES (team_id, game_id) values (1,3);
insert into TB_TEAMS_GAMES (team_id, game_id) values (2,4);
insert into TB_TEAMS_GAMES (team_id, game_id) values (2,5);
insert into TB_TEAMS_GAMES (team_id, game_id) values (3,6);
insert into TB_TEAMS_GAMES (team_id, game_id) values (3,7);
insert into TB_TEAMS_GAMES (team_id, game_id) values (4,8);
insert into TB_TEAMS_GAMES (team_id, game_id) values (4,9);
insert into TB_TEAMS_GAMES (team_id, game_id) values (4,10);
insert into TB_TEAMS_GAMES (team_id, game_id) values (4,11);
insert into TB_TEAMS_GAMES (team_id, game_id) values (1,12);
insert into TB_TEAMS_GAMES (team_id, game_id) values (1,13);
insert into TB_TEAMS_GAMES (team_id, game_id) values (1,14);
insert into TB_TEAMS_GAMES (team_id, game_id) values (5,15);
insert into TB_TEAMS_GAMES (team_id, game_id) values (5,16);
insert into TB_TEAMS_GAMES (team_id, game_id) values (5,17);
insert into TB_TEAMS_GAMES (team_id, game_id) values (5,18);
insert into TB_TEAMS_GAMES (team_id, game_id) values (5,1);